### CREATE CHECK
POST http://localhost:3000/checks
token: LO1E3MUAk4p1FCPfPqs7lHyyp0uFDr6BjmA2G1o9zu4lyBHp0ZNWxwOtNOmHNHlXrfj9m9toKsLTHIk32eQvCRU1yR7nUzWyQdqYZYE64mB7bXF4Ef4VH4Cq1ez2xer53C4T98kU5FylYlQ14XlqLxcs7pkGQfXygC2i36AYjIEPNNyrnDArU1veLaNJLc55gBnN3odkr1lWdivxYjzMSXquc4JgkEqGzSkrNBB8Bu9zvAOVKpqW3M65KF

{
    "protocol": "https",
    "method": "get",
    "url": "twitter.com",
    "successCodes": [200, 201, "302", "301"],
    "timeoutSeconds": 4
}

### GET CHECK
GET http://localhost:3000/checks?id=KQ1ILbILRIKPDGCNt2PU
token: LO1E3MUAk4p1FCPfPqs7lHyyp0uFDr6BjmA2G1o9zu4lyBHp0ZNWxwOtNOmHNHlXrfj9m9toKsLTHIk32eQvCRU1yR7nUzWyQdqYZYE64mB7bXF4Ef4VH4Cq1ez2xer53C4T98kU5FylYlQ14XlqLxcs7pkGQfXygC2i36AYjIEPNNyrnDArU1veLaNJLc55gBnN3odkr1lWdivxYjzMSXquc4JgkEqGzSkrNBB8Bu9zvAOVKpqW3M65KF

### UPDATE CHECK
PUT http://localhost:3000/checks
token: LO1E3MUAk4p1FCPfPqs7lHyyp0uFDr6BjmA2G1o9zu4lyBHp0ZNWxwOtNOmHNHlXrfj9m9toKsLTHIk32eQvCRU1yR7nUzWyQdqYZYE64mB7bXF4Ef4VH4Cq1ez2xer53C4T98kU5FylYlQ14XlqLxcs7pkGQfXygC2i36AYjIEPNNyrnDArU1veLaNJLc55gBnN3odkr1lWdivxYjzMSXquc4JgkEqGzSkrNBB8Bu9zvAOVKpqW3M65KF

{
    "id": "HfjRCrghv2n7cbLBnk7X",
    "protocol": "https",
    "method": "post",
    "timeoutSeconds": 5
}

### DELETE CHECK
DELETE http://localhost:3000/checks?id=BDxpYKslB21KzyXbz0hK
token: LO1E3MUAk4p1FCPfPqs7lHyyp0uFDr6BjmA2G1o9zu4lyBHp0ZNWxwOtNOmHNHlXrfj9m9toKsLTHIk32eQvCRU1yR7nUzWyQdqYZYE64mB7bXF4Ef4VH4Cq1ez2xer53C4T98kU5FylYlQ14XlqLxcs7pkGQfXygC2i36AYjIEPNNyrnDArU1veLaNJLc55gBnN3odkr1lWdivxYjzMSXquc4JgkEqGzSkrNBB8Bu9zvAOVKpqW3M65KF