### CREATE CHECK
POST http://localhost:3000/checks
token: bYtfrWQqopm7L5qy3QSkCmpbTN1hfeWv91CsX2Hco65VzWw5eoLtbbekYbfj8pnjnJAhJeeCByildrqPRVugk59ckf0io73qMOVH5ADQK5FLqWXrQ0qqXRMr6bofxEuxaALBRTZtdFapUYKSxB42SNiMn1Mrp5YsezrWDQDGeby2dZnk8bwcJx96PvBWn63be23ajOMPIYni9mULre2telRtbIz7UezpZjiDVEZ6M18IADeZ99sbXBHEqs

{
    "protocol": "http",
    "method": "get",
    "url": "google.com",
    "successCodes": [200, 201, "200"],
    "timeoutSeconds": 4
}

### GET CHECK
GET http://localhost:3000/checks?id=uiQkPdy9QlyxIYI1y2PI
token: bYtfrWQqopm7L5qy3QSkCmpbTN1hfeWv91CsX2Hco65VzWw5eoLtbbekYbfj8pnjnJAhJeeCByildrqPRVugk59ckf0io73qMOVH5ADQK5FLqWXrQ0qqXRMr6bofxEuxaALBRTZtdFapUYKSxB42SNiMn1Mrp5YsezrWDQDGeby2dZnk8bwcJx96PvBWn63be23ajOMPIYni9mULre2telRtbIz7UezpZjiDVEZ6M18IADeZ99sbXBHEqs

### UPDATE CHECK
PUT http://localhost:3000/checks
token: bYtfrWQqopm7L5qy3QSkCmpbTN1hfeWv91CsX2Hco65VzWw5eoLtbbekYbfj8pnjnJAhJeeCByildrqPRVugk59ckf0io73qMOVH5ADQK5FLqWXrQ0qqXRMr6bofxEuxaALBRTZtdFapUYKSxB42SNiMn1Mrp5YsezrWDQDGeby2dZnk8bwcJx96PvBWn63be23ajOMPIYni9mULre2telRtbIz7UezpZjiDVEZ6M18IADeZ99sbXBHEqs

{
    "id": "HfjRCrghv2n7cbLBnk7X",
    "protocol": "https",
    "method": "post",
    "timeoutSeconds": 5
}

### DELETE CHECK
DELETE http://localhost:3000/checks?id=BDxpYKslB21KzyXbz0hK
token: bYtfrWQqopm7L5qy3QSkCmpbTN1hfeWv91CsX2Hco65VzWw5eoLtbbekYbfj8pnjnJAhJeeCByildrqPRVugk59ckf0io73qMOVH5ADQK5FLqWXrQ0qqXRMr6bofxEuxaALBRTZtdFapUYKSxB42SNiMn1Mrp5YsezrWDQDGeby2dZnk8bwcJx96PvBWn63be23ajOMPIYni9mULre2telRtbIz7UezpZjiDVEZ6M18IADeZ99sbXBHEqs