### CREATE TOKEN
POST http://localhost:3000/tokens

{
    "email": "ifeoluwaolubo@gmail.com",
    "password": "12345678"
}

### GET TOKEN
GET http://localhost:3000/tokens?token=0QgbaMLRTrMDfQtPeBcqCWupajDED3Zz8VfuilaU3xH0ymu6p4DzXFu3YMGUzcUKdu3phGLZsraGfpYdPcQTMMVzrDh6NJaJBNlkBMozg79ch236CsXKVE0G2SyxgcB0DjwliJwOtXP2ifXI7TBA5d5q6Sk94iktbkqDdahd0cYXim5LmMB6LVe9cuskZucrkzCg7gqVlUYPtNYevaCgFxrJnzA1NNuvoGahk62NZjNIrl9RwWDN4nHF5i

### GET TOKEN
PUT http://localhost:3000/tokens

{
    "token": "0QgbaMLRTrMDfQtPeBcqCWupajDED3Zz8VfuilaU3xH0ymu6p4DzXFu3YMGUzcUKdu3phGLZsraGfpYdPcQTMMVzrDh6NJaJBNlkBMozg79ch236CsXKVE0G2SyxgcB0DjwliJwOtXP2ifXI7TBA5d5q6Sk94iktbkqDdahd0cYXim5LmMB6LVe9cuskZucrkzCg7gqVlUYPtNYevaCgFxrJnzA1NNuvoGahk62NZjNIrl9RwWDN4nHF5i",
    "extend": true
}