### CREATE USERS
POST http://localhost:3000/users

{
    "firstName": "Ifeoluwa",
    "lastName": "Olubo",
    "email": "ifeoluwaolubo+1@gmail.com",
    "phoneNumber": "08084356673",
    "password": "12345678",
    "tosAgreement": true
}

### GET USERS
GET http://localhost:3000/users?email=ifeoluwaolubo@gmail.com

### UPDATE USERS
PUT http://localhost:3000/users

{
    "email": "ifeoluwaolubo@gmail.com",
    "phoneNumber": "09028849304"
}

### UPDATE USERS
DELETE http://localhost:3000/users?email=ifeoluwaolubo+1@gmail.com