### CREATE USERS
POST http://localhost:3000/users

{
    "firstName": "Ifeoluwa",
    "lastName": "Olubo",
    "email": "ifeoluwaolubo@gmail.com",
    "phoneNumber": "08084356673",
    "password": "12345678",
    "tosAgreement": true
}

### GET USERS
GET http://localhost:3000/users?email=ifeoluwaolubo@gmail.com
token: KL6AcEQpW8o2ndy71fNHDMuZk6fBu8eYNuEOnZpH1dk0AytXxU14Azxj1wFmR1yaypgV22MooX5e3bGP9mw3RkjSr3VFfSF3M1em8IjgxikJPYOuBhN2e4v0SF9FxnEoYnzDUVOZrxBq5bIRP26HOmMTEyJG8Pu8dPfSzfJTzCDqt9BHiUJ27UAq3jn23nv27pkicx9mjwbDkSKKgrD5ybD55MLq1tP5hvTqh6Erz9w7eVVS76chpaLzQ6

### UPDATE USERS
PUT http://localhost:3000/users
token: KL6AcEQpW8o2ndy71fNHDMuZk6fBu8eYNuEOnZpH1dk0AytXxU14Azxj1wFmR1yaypgV22MooX5e3bGP9mw3RkjSr3VFfSF3M1em8IjgxikJPYOuBhN2e4v0SF9FxnEoYnzDUVOZrxBq5bIRP26HOmMTEyJG8Pu8dPfSzfJTzCDqt9BHiUJ27UAq3jn23nv27pkicx9mjwbDkSKKgrD5ybD55MLq1tP5hvTqh6Erz9w7eVVS76chpaLzQ6

{
    "email": "ifeoluwaolubo@gmail.com",
    "phoneNumber": "09028849304"
}

### DELETE USER
DELETE http://localhost:3000/users?email=ifeoluwaolubo@gmail.com
token: KL6AcEQpW8o2ndy71fNHDMuZk6fBu8eYNuEOnZpH1dk0AytXxU14Azxj1wFmR1yaypgV22MooX5e3bGP9mw3RkjSr3VFfSF3M1em8IjgxikJPYOuBhN2e4v0SF9FxnEoYnzDUVOZrxBq5bIRP26HOmMTEyJG8Pu8dPfSzfJTzCDqt9BHiUJ27UAq3jn23nv27pkicx9mjwbDkSKKgrD5ybD55MLq1tP5hvTqh6Erz9w7eVVS76chpaLzQ6